# Generated by Django 2.2.7 on 2019-11-23 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('write', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='write',
            name='url',
        ),
    ]
