# Generated by Django 2.2.7 on 2019-11-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write', '0003_auto_20191124_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='write',
            name='upvotes_total',
            field=models.IntegerField(default=1),
        ),
    ]
