# Generated by Django 2.2.7 on 2019-11-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write', '0004_auto_20191124_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='write',
            name='category',
            field=models.CharField(choices=[('tech', '#tech'), ('politics', '#politics'), ('history', '#history'), ('health', '#health'), ('education', '#education'), ('sports', '#sports'), ('family', '#family'), ('food', '#food'), ('news', '#news')], default='tech', max_length=1),
        ),
    ]
